# Generated by Django 2.1.7 on 2019-02-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chocice',
            new_name='Choice',
        ),
    ]
